server: localhost:9000
token: sample_token
proxies:
  ssh:
    type: tcp
    local_port: 22
    remote_port: 6000
  web:
    type: tcp
    local_port: 8080
    remote_port: 8000
  game:
    type: udp
    local_port: 7777
    remote_port: 7777
  # Add more proxies as needed
