server: localhost:9000
token: 0196e9bd-dab3-7d51-a89c-4fcc68e3a811
proxies:
  ssh:
    type: tcp
    local_port: 22
    remote_port: 6000
  web:
    type: tcp
    local_port: 8080
    remote_port: 8000
