# TLS certificate and key paths
enable_tls: true
tls_cert_file: ~/repos/mgrok/certs/localhost+2.pem
tls_key_file: ~/repos/mgrok/certs/localhost+2-key.pem

# Server configuration
bind_addr: 127.0.0.1
bind_port: 9000

# Security settings (disabled for development)
auth_token: sample_token

# Port range for automatic assignment
port_range_start: 10000
port_range_end: 20000
# Allowed clients (for production use)
# allowed_clients:
#   - token: client1_token
#     name: client1
#     allowed_ports: [8000, 8001, 8080]
#   - token: client2_token
#     name: client2
#     allowed_ports: [9000-9100]
