# Server configuration
bind_addr: 0.0.0.0
bind_port: 9000

# Security settings (disabled for development)
auth_token: sample_token
enable_tls: false

# Port range for automatic assignment
port_range_start: 10000
port_range_end: 20000
# Allowed clients (for production use)
# allowed_clients:
#   - token: client1_token
#     name: client1
#     allowed_ports: [8000, 8001, 8080]
#   - token: client2_token
#     name: client2
#     allowed_ports: [9000-9100]
