# TLS certificate and key paths
enable_tls: true
tls_cert_file: ~/repos/mgrok/certs/localhost+2.pem
tls_key_file: ~/repos/mgrok/certs/localhost+2-key.pem

# Server configuration
bind_addr: 127.0.0.1
bind_port: 9000
auth_token: 0196e9bd-dab3-7d51-a89c-4fcc68e3a811

# Port range for automatic assignment
port_range_start: 10000
port_range_end: 20000
